
/* THE GREAT DUNING QUERY */

SELECT 
	 u.CUSTOMER_ID,
	 u.CUSTCODE,
	 u.LBC_DATE,
	 t.CO_ID,
	 v.OHINVAMT_GL "Invoice Amount",
	 v.OHOPNAMT_GL "Open Amount" ,
	 v.OHDUEDATE,
	 q.DN_NUM ,
	 p.CCLNAME ,
	 p.CCEMAIL
FROM 
     CUSTOMER_ALL u ,
	 ORDERHDR_ALL v,
	 DIRECTORY_NUMBER q,
	 CCONTACT_ALL p ,
	 CONTR_SERVICES_CAP s,
	 CONTRACT_ALL t
WHERE
	 v.OHSTATUS = 'IN'
AND	 v.OHINVTYPE = 5
AND	 v.OHOPNAMT_GL > 0
AND	 u.CSTYPE = 'a'
AND  p.CSCUSTTYPE = 'C'
AND  v.CUSTOMER_ID = u.CUSTOMER_ID
AND  u.CUSTOMER_ID = p.CUSTOMER_ID
AND  t.CUSTOMER_ID = p.CUSTOMER_ID
AND  t.CO_ID = s.CO_ID
AND  s.DN_ID = q.DN_ID ;




/* THE GREAT DUNING QUERY OPTIMISÉE enfin presque */

SELECT 
	 u.CUSTOMER_ID,
	 u.CUSTCODE,
	 u.LBC_DATE,
	 v.OHINVAMT_GL "Invoice Amount",
	 v.OHOPNAMT_GL "Open Amount" ,
	 v.OHDUEDATE
FROM 
     CUSTOMER_ALL u ,
	 ORDERHDR_ALL v,
	 CCONTACT_ALL p 
WHERE
	 v.OHSTATUS = 'IN'
AND	 v.OHINVTYPE = 5
AND	 v.OHOPNAMT_GL > 0
AND	 u.CSTYPE = 'a'
AND  p.CSCUSTTYPE = 'C'
AND  v.CUSTOMER_ID = u.CUSTOMER_ID
AND  u.CUSTOMER_ID = p.CUSTOMER_ID

/* TEST CLIENT CORPO ELIGIBLE D'UN Bill Cycle Donné */



SELECT 
     v.CUSTOMER_ID , v.OHENTDATE 
FROM 
     ORDERHDR_ALL v ,
     CUSTOMER_ALL u      
WHERE
     v.OHSTATUS = 'IN'
AND     v.OHINVTYPE = 5
AND     v.OHOPNAMT_GL > 0
AND   v.OHENTDATE = to_date('08/04/20' ,'DD/MM/YYYY')
AND v.CUSTOMER_ID = u.CUSTOMER_ID
AND u.TMCODE IN 
(SELECT TMCODE
FROM OFFER_TYPE 
WHERE TYPE = 'C')



