/*CUSTOMER*/
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMERS (
CUSTOMER_ID INTEGER ,
CUSTCODE VARCHAR(32 BYTE) ,
SEGMENT VARCHAR2(100 BYTE) ,
INVOICE_AMOUNT INTEGER ,
OPEN_AMOUNT FLOAT ,
DUE_DATE DATE ,
LBC_DATE DATE ,
CCLNAME VARCHAR2(40 BYTE) ,
MSISDN VARCHAR2(100  BYTE) ,
CCEMAIL VARCHAR2(200 BYTE) ,
CONSTRAINT PK_DUNNING_ELIGIBLE_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
CONSTRAINT NTNLL_CUSTCODE CHECK (CUSTCODE IS NOT NULL),
CONSTRAINT UNQ_CUSTCODE UNIQUE (CUSTCODE),
CONSTRAINT CHK_INVOICE_AMOUNT CHECK (INVOICE_AMOUNT > 0) ,
CONSTRAINT CHK_OPEN_AMOUNT CHECK (OPEN_AMOUNT > 0) ,
CONSTRAINT NTNLL_CCLNAME CHECK (CCLNAME IS NOT NULL) ,
CONSTRAINT CHK_CCEMAIL CHECK (CCEMAIL LIKE '%@%.%')  ,
CONSTRAINT NTNLL_MSISDN CHECK (MSISDN IS NOT NULL) ,
CONSTRAINT CHK_LBC_DATE_DUE_DATE CHECK (LBC_DATE < DUE_DATE) 
);
/*PLNIFICATION*/
/*ALERTE*/
/*USER*/

